import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { bulkHeadline, bulkNotes, bulkResultLine, bulkTransitions, explainBulkError, parseBulkProposal, undoResultLine } from './bulkChange.mjs';

// Generated by the Backend's own preview code, so the card is tested against what it really sends.
const real = JSON.parse(readFileSync(new URL('./fixtures/bulk.sample.json', import.meta.url), 'utf8'));

test('a real update preview parses and reads in plain words', () => {
  const b = parseBulkProposal(real.update);
  assert.equal(b.action, 'update');
  assert.equal(b.willChange, 3);
  assert.equal(bulkHeadline(b), 'Set status to closed on 3 records in orders');
  assert.deepEqual(b.where, ['status is open']);
  assert.deepEqual(bulkTransitions(b), [{ field: 'status', from: 'open (3)', to: 'closed' }]);
  assert.equal(b.sample[0].label, 'Order 1001');
  assert.deepEqual(b.sample[0].changes, [{ field: 'status', before: 'open', after: 'closed' }]);
  assert.match(bulkNotes(b).join(' '), /undo this for 30 days/);
});

test('a real delete preview says trash and the restore window', () => {
  const b = parseBulkProposal(real.delete);
  assert.equal(b.action, 'delete');
  assert.equal(bulkHeadline(b), 'Move 2 records in orders to the trash');
  assert.match(bulkNotes(b).join(' '), /stay in the trash for 30 days/);
});

test('the browser never receives the record list, and a stray one is ignored', () => {
  assert.ok(!('items' in real.update));
  const b = parseBulkProposal({ ...real.update, items: [{ id: 'x' }], set_exact: { status: 'hacked' } });
  assert.ok(!('items' in b));
  assert.ok(!JSON.stringify(b).includes('hacked'));
});

test('unusable payloads give no card instead of a broken one', () => {
  for (const bad of [null, 'x', {}, { ...real.update, type: 'other' }, { ...real.update, preview_id: '' }, { ...real.update, will_change: 0 },
    { ...real.update, will_change: 99 }, { ...real.update, matched: -1 }, { ...real.update, action: 'drop' }, { ...real.update, set: {} },
    { ...real.update, will_change: 1.5 }, { ...real.update, matched: Infinity }]) {
    assert.equal(parseBulkProposal(bad), null, JSON.stringify(bad).slice(0, 60));
  }
});

test('text from the data is plain, bounded and cannot carry markup or hidden characters', () => {
  const evil = { ...real.update, api_name: '<img src=x onerror=alert(1)>' + 'a'.repeat(200), where: ['x‮evil​'.padEnd(500, 'y')],
    sample: [{ id: 'r1', label: 'a\u0000b', changes: [{ field: 'f', before: { nested: 1 }, after: NaN }] }] };
  const b = parseBulkProposal(evil);
  assert.ok(b.object.length <= 80);
  assert.ok(b.where[0].length <= 160);
  assert.ok(!/[‮​]/.test(b.where[0]));
  assert.equal(b.sample[0].label, 'a b');
  assert.deepEqual(b.sample[0].changes[0], { field: 'f', before: null, after: null });
});

test('lists are capped', () => {
  const many = { ...real.update, sample: Array.from({ length: 40 }, (_, i) => ({ id: `r${i}`, label: 'l', changes: Array.from({ length: 30 }, (_, j) => ({ field: `f${j}`, before: 1, after: 2 })) })) };
  const b = parseBulkProposal(many);
  assert.equal(b.sample.length, 8);
  assert.equal(b.sample[0].changes.length, 6);
});

test('records that already match are called out', () => {
  const b = parseBulkProposal({ ...real.update, matched: 5, will_change: 3 });
  assert.equal(b.unchanged, 2);
  assert.match(bulkNotes(b)[0], /2 records that match already have these values/);
});

test('results are described exactly, including what was skipped or left alone', () => {
  assert.equal(bulkResultLine({ changed: 3, skipped: 0 }), 'Changed 3 records.');
  assert.equal(bulkResultLine({ changed: 1, skipped: 1 }), 'Changed 1 record. 1 record was skipped because it was edited after the preview.');
  assert.equal(bulkResultLine(null), 'Changed 0 records.');
  assert.equal(undoResultLine({ restored: 2, left_alone: 1 }), 'Put back 2 records. 1 record was left as is because it was edited since.');
  assert.equal(undoResultLine({ restored: 3, left_alone: 0 }), 'Put back 3 records.');
});

test('errors are explained plainly', () => {
  assert.match(explainBulkError(401), /Sign in/);
  assert.match(explainBulkError(404), /no longer exists/);
  assert.match(explainBulkError(400, 'This preview has expired.'), /fresh preview/);
  assert.equal(explainBulkError(500, 'Boom'), 'Boom');
  assert.equal(explainBulkError(500), 'The change could not be applied.');
});
