import { WidgetSpec } from './chatApi';

export interface DashboardTemplate {
  id: string;
  name: string;
  description: string;
  category: 'Revenue' | 'Marketing' | 'Telemetry' | 'Finance' | 'General';
  badge: string;
  badgeColor: string;
  iconName: 'chart-arrows' | 'target' | 'activity' | 'report-money' | 'file-plus';
  tags: string[];
  widgets: WidgetSpec[];
}

export const CURATED_TEMPLATES: DashboardTemplate[] = [
  {
    id: 'sales_revenue',
    name: 'Sales & Revenue Velocity',
    description: 'Executive revenue pulse: track MRR velocity, ARR forecast, funnel conversion, and net retention.',
    category: 'Revenue',
    badge: 'Popular',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    iconName: 'chart-arrows',
    tags: ['SaaS', 'MRR', 'Pipeline', 'Cohort'],
    widgets: [
      {
        id: 'w-sales-mrr',
        type: 'metric_card',
        component: 'metric_card',
        title: 'Monthly Recurring Revenue',
        value: '$148,200',
        change: '+14.2% MoM',
        trend: 'up',
        positive: true,
        span: 1,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-sales-net-retention',
        type: 'metric_card',
        component: 'metric_card',
        title: 'Net Revenue Retention',
        value: '118.4%',
        change: '+2.8% QoQ',
        trend: 'up',
        positive: true,
        span: 1,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-sales-arr-trajectory',
        type: 'line_chart',
        component: 'line_chart',
        title: 'ARR Growth Trajectory ($k)',
        series: [
          { x: 'Jan', y: 840 },
          { x: 'Feb', y: 920 },
          { x: 'Mar', y: 1050 },
          { x: 'Apr', y: 1180 },
          { x: 'May', y: 1320 },
          { x: 'Jun', y: 1490 },
          { x: 'Jul', y: 1620 },
          { x: 'Aug', y: 1778 },
        ],
        unit: '$k',
        timeframe: 'Last 8 Months',
        span: 2,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-sales-funnel',
        type: 'funnel',
        component: 'funnel',
        title: 'Enterprise Pipeline Funnel',
        props: {
          title: 'Enterprise Pipeline Funnel',
          stages: [
            { label: 'Raw Inbound Inquiries', value: 4200, percent: 100 },
            { label: 'Marketing Qualified (MQL)', value: 1840, percent: 43.8 },
            { label: 'Sales Accepted (SAL)', value: 920, percent: 21.9 },
            { label: 'Technical Evaluation', value: 340, percent: 8.1 },
            { label: 'Closed / Won Enterprise', value: 142, percent: 3.4 },
          ],
        },
        span: 2,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-sales-expansion-table',
        type: 'table',
        component: 'table',
        title: 'Recent Enterprise Expansions',
        columns: ['Account Name', 'Tier', 'Expansion ARR', 'Status', 'Quarter'],
        rows: [
          ['Acme Global Corp', 'Enterprise Plus', '$48,000', 'Signed', 'Q3'],
          ['Helix Genomics', 'Enterprise Core', '$32,500', 'Signed', 'Q3'],
          ['Vanguard Logistics', 'Enterprise Plus', '$65,000', 'Contract Sent', 'Q3'],
          ['Sovereign Cloud AI', 'Custom Dedicated', '$110,000', 'In Legal', 'Q3'],
          ['Oasis Financial Labs', 'Enterprise Core', '$24,000', 'Signed', 'Q3'],
        ],
        span: 2,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 'marketing_analytics',
    name: 'Growth & Marketing Attribution',
    description: 'Full-funnel marketing intelligence: Blended CAC, organic discovery velocity, and multi-channel attribution.',
    category: 'Marketing',
    badge: 'Growth',
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    iconName: 'target',
    tags: ['Attribution', 'CAC', 'LTV', 'Channels'],
    widgets: [
      {
        id: 'w-mkt-cac',
        type: 'metric_card',
        component: 'metric_card',
        title: 'Blended CAC',
        value: '$342',
        change: '-11.2% vs target',
        trend: 'down',
        positive: true,
        span: 1,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-mkt-ltv-cac',
        type: 'metric_card',
        component: 'metric_card',
        title: 'LTV : CAC Ratio',
        value: '4.8x',
        change: '+0.6x YoY',
        trend: 'up',
        positive: true,
        span: 1,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-mkt-channels',
        type: 'bar_chart',
        component: 'bar_chart',
        title: 'Qualified Pipeline by Channel ($k)',
        series: [
          { label: 'Direct / Word-of-mouth', y: 480 },
          { label: 'Technical SEO & Docs', y: 395 },
          { label: 'Developer Events', y: 260 },
          { label: 'Partner Referrals', y: 195 },
          { label: 'Targeted Search', y: 140 },
        ],
        unit: '$k',
        span: 2,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-mkt-conversion-timeline',
        type: 'timeline',
        component: 'timeline',
        title: 'Key Product Releases & Acquisition Surges',
        events: [
          { date: 'Aug 14', label: 'Launch on Hacker News', description: 'Surge of 14,200 unique developers and 280 team signups.' },
          { date: 'Aug 22', label: 'AnalyzeIt 2.0 GA Release', description: 'Terracotta dark mode & agentic canvas architecture announced.' },
          { date: 'Sep 02', label: 'Enterprise SOC2 Certification', description: 'Unlocked 12 delayed enterprise compliance reviews.' },
        ],
        span: 2,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 'ops_telemetry',
    name: 'Mesh Operations & Edge Telemetry',
    description: 'Real-time telemetry command center: P99 edge latency, node availability, and active cluster health.',
    category: 'Telemetry',
    badge: 'Real-time',
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    iconName: 'activity',
    tags: ['Edge', 'Latency', 'P99', 'Uptime'],
    widgets: [
      {
        id: 'w-ops-uptime',
        type: 'metric_card',
        component: 'metric_card',
        title: 'Edge Cluster Availability',
        value: '99.988%',
        change: '+0.012% (30d)',
        trend: 'up',
        positive: true,
        span: 1,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-ops-p99-latency',
        type: 'metric_card',
        component: 'metric_card',
        title: 'Global P99 Edge Latency',
        value: '18.4ms',
        change: '-3.2ms after CDN migration',
        trend: 'down',
        positive: true,
        span: 1,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-ops-alert',
        type: 'alert_banner',
        component: 'alert_banner',
        title: 'Telemetry Advisory',
        props: {
          title: 'Telemetry Advisory: Zero Edge Degraded',
          severity: 'info',
          message: 'All 10 regional points of presence are operating nominally. Automatic BGP failover verified.',
          action_label: 'View Edge Topology',
        },
        span: 2,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-ops-nodes-table',
        type: 'table',
        component: 'table',
        title: 'Regional Telemetry Hub Status',
        columns: ['Region', 'Data Center', 'Throughput', 'Status', 'P99 Latency'],
        rows: [
          ['US-East (N. Virginia)', 'iad-edge-01', '4.2 GB/s', 'Healthy', '12ms'],
          ['US-West (Oregon)', 'pdx-edge-02', '3.1 GB/s', 'Healthy', '14ms'],
          ['EU-West (Frankfurt)', 'fra-edge-01', '2.8 GB/s', 'Healthy', '18ms'],
          ['AP-South (Mumbai)', 'bom-edge-01', '1.9 GB/s', 'Healthy', '26ms'],
          ['AP-East (Tokyo)', 'hnd-edge-01', '2.2 GB/s', 'Healthy', '22ms'],
        ],
        span: 2,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 'finance_pnl',
    name: 'Finance & Treasury P&L',
    description: 'Board-ready capital telemetry: Gross margins, cash burn rate, runway projections, and departmental OpEx.',
    category: 'Finance',
    badge: 'Executive',
    badgeColor: 'bg-violet-500/10 text-violet-400 border-violet-500/20',
    iconName: 'report-money',
    tags: ['P&L', 'Runway', 'Burn Rate', 'OpEx'],
    widgets: [
      {
        id: 'w-fin-margin',
        type: 'metric_card',
        component: 'metric_card',
        title: 'Software Gross Margin',
        value: '79.2%',
        change: '+1.8% vs last quarter',
        trend: 'up',
        positive: true,
        span: 1,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-fin-runway',
        type: 'metric_card',
        component: 'metric_card',
        title: 'Treasury Runway',
        value: '26.4 Months',
        change: 'Net Burn: $62k / mo',
        trend: 'flat',
        positive: true,
        span: 1,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
      {
        id: 'w-fin-opex-breakdown',
        type: 'table',
        component: 'table',
        title: 'Departmental Monthly OpEx Budget',
        columns: ['Cost Center', 'Actual ($)', 'Budget ($)', 'Variance', 'Trajectory'],
        rows: [
          ['Engineering & Core AI', '$124,000', '$130,000', '-$6,000', 'Under budget'],
          ['Infrastructure & Compute', '$48,500', '$50,000', '-$1,500', 'Nominal'],
          ['Product Design & UX', '$32,000', '$32,000', '$0', 'On target'],
          ['Growth & Marketing', '$28,400', '$30,000', '-$1,600', 'Optimized'],
          ['Legal & Compliance', '$12,000', '$15,000', '-$3,000', 'Completed'],
        ],
        span: 2,
        provenance: {
          kind: 'synthetic_ai',
          source: 'Curated template · sample data',
          timestamp: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 'blank_canvas',
    name: 'Blank Agentic Canvas',
    description: 'Start with a clean slate. Build custom layout from scratch or prompt the AI agent to synthesize widgets.',
    category: 'General',
    badge: 'Clean Slate',
    badgeColor: 'bg-stone-500/10 text-stone-400 border-stone-500/20',
    iconName: 'file-plus',
    tags: ['Custom', 'Blank', 'Ad-hoc', 'Flexible'],
    widgets: [],
  },
];
